
alg: PIQL
alg_kwargs:
  beta: 0.3333
  expectile: 0.7
  reward_steps: 50000

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorCriticValueRewardPolicy
network_kwargs:
  encoder_class: DrQv2Encoder
  actor_class: DrQv2Actor
  actor_kwargs:
    dropout: 0.5 # only actor gets dropout sometimes.
    output_act: ["import", "torch.nn", "Tanh"]
  critic_class: DrQv2Critic
  critic_kwargs:
    ensemble_size: 2
  value_class: DrQv2Value
  value_kwargs:
    ensemble_size: 1
  reward_class: DrQv2Reward
  reward_kwargs:
    ensemble_size: 1

checkpoint: null

eval_env: mw_plate-slide-image-v2


dataset: FeedbackBuffer
dataset_kwargs:
  path: datasets/mw/pref_image/mw_drawer-open-v2_ep2500_n0.3_img64.npz
  batch_size: 48
  segment_length: null # default to 64
  capacity: 10000 # How many comparisons to allow, null means all in the dataset.
  label_key: rl_sum
  mode: comparison
  discount: 0.99

processor: RandomCrop

schedule:
  actor: ["import", "torch.optim.lr_scheduler", "CosineAnnealingLR"]
schedule_kwargs:
  actor:
    T_max: 200000


trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 200000 # The total number of steps to train
  log_freq: 500 # How often to log values
  profile_freq: 500
  eval_freq: 2500 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 25 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 1 # Number of dataloader workers.
    batch_size: null
  benchmark: True

seed: null
