
alg: BehaviorCloning
alg_kwargs:
  bc_all_steps: 80000
  bc_data: pos

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorPolicy
network_kwargs:
  encoder_class: DrQv2Encoder
  actor_class: DrQv2Actor
  actor_kwargs:
    output_act: ["import", "torch.nn", "Tanh"]
    dropout: 0.5

checkpoint: null

eval_env: mw_drawer-open-image-v2

dataset: FeedbackBuffer
dataset_kwargs:
  path: datasets/mw/pref_image/mw_drawer-open-v2_ep2500_n0.3_img64.npz
  batch_size: 48
  segment_length: null # default to 64
  capacity: 10000 # How many comparisons to allow, null means all in the dataset.
  label_key: rl_sum
  mode: comparison

processor: RandomCrop

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 200000 # The total number of steps to train
  log_freq: 500 # How often to log values
  profile_freq: 500
  eval_freq: 2500 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 25 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 1 # Number of dataloader workers.
    batch_size: null
  benchmark: True

seed: null
